import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import Head from 'next/head';
import Header from '../_components/Header';
import Main from '../_components/Main';
import Projects from '../_components/Projects';

import axios from 'axios';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import { BASE_URL } from '@/api';

function Product() {
  const router = useRouter().query.id;
  const [products, setProducts] = useState();

  useEffect(() => {
    axios
      .get(`${BASE_URL}/projects/${router}`)
      .then((res) => setProducts(res?.data?.data))
      .catch((err) => console.log(err));
  }, [router]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
      </nav>
      <header>
        <Header products={products} />
      </header>
      <main>
        <Main products={products} />
      </main>
      <section>
        <Projects />
      </section>
      <footer>
        <Footer />
      </footer>
    </>
  );
}

export default Product;
