import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import Head from 'next/head';
import React from 'react';
import Header from './_components/Header';
import Main from './_components/Main';
import Link from 'next/link';
import Form from './_components/Form';

function Service() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
      </nav>
      <header>
        <Header />
      </header>
      <main>
        <Main />
        <Form />
      </main>
      <footer>
        <Footer />
      </footer>
      <Link className="position-link" href={'/alstar-product/19cd21bb-10e4-4908-b170-fe9805cc4991'}>
        ALSTAR™ A2
      </Link>
    </>
  );
}

export default Service;
