import Design from "@/components/Design";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import News from "@/components/News";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <nav>
          <Navbar />
        </nav>
        <header>
          <Header />
        </header>
        <main>
          <Design />
          <News />
        </main>
        <footer></footer>
      </>
    </>
  );
}
